/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/client/**/*.{vue,ts,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "cb-bg": "var(--color-bg)",
        "cb-bg-deep": "var(--color-bg-deep)",
        "cb-surface": "var(--color-surface)",
        "cb-surface-2": "var(--color-surface-2)",
        "cb-surface-dark": "var(--color-surface-dark)",
        "cb-border": "var(--color-border)",
        "cb-border-strong": "var(--color-border-strong)",
        "cb-text": "var(--color-text)",
        "cb-text-secondary": "var(--color-text-secondary)",
        "cb-text-muted": "var(--color-text-muted)",
        "cb-text-dim": "var(--color-text-dim)",
        "cb-text-bright": "var(--color-text-bright)",
        "cb-primary": "var(--color-primary)",
        "cb-accent": "var(--color-accent)",
        "cb-highlight": "var(--color-highlight)",
        "cb-warning": "var(--color-warning)",
        "cb-toolbar-bg": "var(--color-toolbar-bg)",
        "cb-toolbar-btn-bg": "var(--color-toolbar-btn-bg)",
        "cb-toolbar-btn-border": "var(--color-toolbar-btn-border)",
        "cb-toolbar-btn-active-bg": "var(--color-toolbar-btn-active-bg)",
        "cb-toolbar-btn-primary-bg": "var(--color-toolbar-btn-primary-bg)",
        "cb-toolbar-btn-disabled-bg": "var(--color-toolbar-btn-disabled-bg)",
        "cb-toolbar-btn-disabled-border": "var(--color-toolbar-btn-disabled-border)",
        "cb-toolbar-divider": "var(--color-toolbar-divider)",
        "cb-stream-placeholder-bg": "var(--color-stream-placeholder-bg)",
        "cb-stream-placeholder-border": "var(--color-stream-placeholder-border)",
        "cb-stream-screen-bg": "var(--color-stream-screen-bg)",
        "cb-stream-screen-border": "var(--color-stream-screen-border)",
        "cb-stream-screen-text": "var(--color-stream-screen-text)",
        "cb-video-bg": "var(--color-video-bg)",
      },
    },
  },
  plugins: [],
};
